### ISSUE TITLE
Try detect local libs

### ISSUE THREAD

**Issue by miki725** [miki725/importanize#13]
Instead of relying on config file to determine local libraries, try to determine that automatically.
Perhaps the heuristic could be something like:

```
is_local = not stdlib()
           and importable(with sys.path stripped to only allow local imports)
```

**Comment by kgaughan** [comment]
If it's not possible to automatically detect the local package, one alternative might be to allow them to be listed in the configuration file, and/or on the command line.

**Comment by miki725** [comment]
@kgaughan specifying it in config is the current behavior. the idea of this ticket is to try to determine that automatically. not sure how more complex configs can be added via command line so I think it should remain configuration based or automatically generate the config if proper heuristic can be determined

**Comment by PamelaM** [comment]
I think a built-in "site-packages" group (similar to "stdlib" group) would be useful, even if not automatic.

**Comment by miki725** [comment]
hmm. interesting idea. I usually use `remainder` and list local libs explicitly but the reverse actually makes sense.

**Comment by PamelaM** [comment]
See https://github.com/miki725/importanize/pull/34

**Comment by miki725** [comment]
closing since `site-packages` is already merged and released
