### ISSUE TITLE
comments in import produce invalid syntax

### ISSUE THREAD

**Issue by miki725** [miki725/importanize#21]
```
from a import b, c  # noqa
```

is transformed to:

```
from a import (
    b,
    c  # noqa,
)
```

which is of course invalid syntax

**Comment by miki725** [comment]
another note about `# noqa` that in order for flake8 to ignore violations, `# noqa` has to be on the block level and not next to each import leaf:

```
from a import (  # noqa
    b,
    c,
)
```

**Comment by x1ah** [comment]
> another note about `# noqa` that in order for flake8 to ignore violations, `# noqa` has to be on the block level and not next to each import leaf:
> 
> ```
> from a import (  # noqa
>     b,
>     c,
> )
> ```

@miki725 This one still here.

![image](https://user-images.githubusercontent.com/14919255/74798303-60f90e00-5308-11ea-9eaf-6d749c62c15d.png)

**Comment by miki725** [comment]
```
❯ echo "from aaaaaaaaaaaaaaaaaaa import ( # noqa
  cccccccccccccccccccc, bbbbbbbbbbbbbbbbbbbb
  )" | importanize
from aaaaaaaaaaaaaaaaaaa import (  # noqa
    bbbbbbbbbbbbbbbbbbbb,
    cccccccccccccccccccc,
)

❯ echo "from aaaaaaaaaaaaaaaaaaa import ( # type: ignore
  cccccccccccccccccccc, bbbbbbbbbbbbbbbbbbbb
  )" | importanize
from aaaaaaaaaaaaaaaaaaa import (  # type: ignore
    bbbbbbbbbbbbbbbbbbbb,
    cccccccccccccccccccc,
)
```

@x1ah try using latest from master branch

**Comment by miki725** [comment]
https://github.com/miki725/importanize/blob/0.7/importanize/parser.py#L11 only accounted for `noqa` whereas latest master accounts for `type` as well https://github.com/miki725/importanize/blob/2a1731431b46fc0c2e71e15f58552916820491a3/importanize/parser.py#L18
