### ISSUE TITLE
Handle `import foo.bar as baz` properly

### ISSUE THREAD

**Issue by purpleP** [miki725/importanize#36]
Right now If I have imported something like this

`import asyncio as aio`

Importanize would wrongfully group it into local imports. I've somewhat traced this issue.

1. is_stdlib wronfully return False for this module. And the module argument is 'asyncio as aio'
2. The module argument is wrong because `parse_import_statement` incorrectly parses `as` import.

Few other notes

It would've been easier probably just to use existing python parser like jedi etc. But if you still want to use your own, then I should say that names like `stem` and `leafs` is somewhat misleading, because for AST as for any other tree it's usually called `node` and `children`.

That's maybe (I might be wrong) the root of the problem. You probably only have `ImportNode` and `ImportLeaf` but the truth is that `import foo.bar as baz` should parse to something like
```
Node ImportStatement
    Node BinaryOperator "AS"
        Node Module "foo.bar", Node Label "baz"
```

**Comment by miki725** [comment]
it is in the plans to switch to more concrete parser. but yes this definitely sounds like a bug
