### ISSUE TITLE
importanize hanging on 0.6.2, works on 0.6.1

### ISSUE THREAD

**Issue by numberoverzero** [miki725/importanize#44]
First, thanks for the great library!  It's a great feeling to leave import hygiene to an automated process.  Let me know what other details I can provide.

## Summary
importanize 0.6.2 hangs indefinitely for relative directories.  The same command succeeds with 0.6.1.

## Repro Steps
Successful commit using 0.6.1: https://github.com/numberoverzero/oga/commit/88193a428253d6c022228776ef038450ba1fb6b5

I've reproduced this with multiple projects, but if it matters at all you can test with this project:

```
git clone https://github.com/numberoverzero/oga.git
cd oga
python3 -m venv --copies .venv
source .venv/bin/activate
pip install importanize==0.6.2
importanize -vvv oga/

^--- hangs forever
```

roll back and importanize succeeds:

```
pip install --force-reinstall importanize==0.6.1
importanize -vvv oga/
```

**Comment by miki725** [comment]
@numberoverzero thanks for the report. can you check with https://github.com/miki725/importanize/pull/45?if that works will make a release

**Comment by numberoverzero** [comment]
I'll give that a try in a minute; thanks for addressing so quickly!

**Comment by numberoverzero** [comment]
success!  I verified that 0.6.2 was still failing, then uninstalled it and ran the command above to grab the targz.  Worked fine, thanks!
