### ISSUE TITLE
Identify which packages are from the Standard Library

### ISSUE THREAD

**Issue by kelly-sovacool** [miki725/importanize#48]
I found this project via [this StackOverflow question](https://stackoverflow.com/questions/22195382/how-to-check-if-a-module-library-package-is-part-of-the-python-standard-library#). I was able to use the code snippet @miki725 posted there to quickly identify which imports in my project are from the Python Standard Library and which are not. It would be a nice little feature if `importanize` had a command-line option to do this.

General idea for the interface:
`$ importanize --print-stdlib-pkgs path/to/python/files`

Possible output example:
```
stdlib packages:
* abc
* collections
* gzip

non-standard packages:
* docopt
* humanize
```

**Comment by kelly-sovacool** [comment]
When it comes time to distribute your code, it's important to identify dependencies that will need to be installed on new machines (which includes non-standard Python packages). For a large codebase with many import statements, it can be cumbersome to manually check which packages are non-standard, especially if it's been a while since you first started using some of them. For me personally, I needed to start running my project on a HPC cluster, so I had to send the sys admin a list of dependencies to install. Based on there being several similar questions on StackOverflow, I think it's safe to say that this is not an uncommon need.

**Comment by miki725** [comment]
seems reasonable although personally I think deps should be managed by the project itself with something like pipenv. but your use-case seems valid so no objections adding it to the lib. although no promises about the timeframe, etc but PRs are welcome 😄
