### ISSUE TITLE
Confused about the imports order.

### ISSUE THREAD

**Issue by x1ah** [miki725/importanize#51]
Hi. According to the suggestion of PEP8,

>Imports should be grouped in the following order:
Standard library imports.
Related third party imports.
Local application/library specific imports.
You should put a blank line between each group of imports.

But during my use. my code:

```python
from flask import g, request

from cmylocalpackage.some.model import func
from cmylocalpageage.another.model import helper
```

after importanize:

```python
from cmylocalpackage.some.model import func
from cmylocalpageage.another.model import helper
from flask import g, request
```

That into a dictionary order. is this a bug?

**Comment by x1ah** [comment]
emmm.. sorry.

**Comment by miki725** [comment]
no worries
