### ISSUE TITLE
bugs when configure add_imports

### ISSUE THREAD

**Issue by x1ah** [miki725/importanize#52]
Hi Miki, just now I have found some bugs about `add_imports`.

demo code like the following:
```python
# coding: utf-8


class Foo(object):
    ...


def hello():
    print("world")
```

importanize config like following:
```json
{
    "after_imports_new_lines": 2,
    "add_imports": [
        "from __future__ import absolute_import"
    ],
    "formatter": "grouped",
    "groups": [
        {
            "type": "stdlib"
        },
        {
            "type": "sitepackages"
        },
        {
            "type": "remainder"
        },
        {
            "type": "packages",
            "packages": ["test"]
        },
        {
            "type": "local"
        }
    ]
}
```

it's all seem good. but when I optimize import it by importanize, output like the following:
```python
from __future__ import absolute_import


# coding: utf-8


class Foo(object):
    ...


def hello():
    print("world")
```

it seems bugs here. I guess you miss the situation that has no import statements? or importanize just tread `# coding: utf-8` like a normal comment? and I add some import statements to that python file, it works fine. Have any idea about this? how can fix it gracefully?

**Comment by miki725** [comment]
@x1ah https://github.com/miki725/importanize/pull/56 fixes this issue although it refactors importanize in other ways. if you can, would you be able to test if that branch fixes your issues? you can install that branch with:

```
pip install https://github.com/miki725/importanize/archive/parsing.zip
```

thanks
