### ISSUE TITLE
I added you to https://pre-commit.com/hooks.html

### ISSUE THREAD

**Issue by asottile** [miki725/importanize#53]
🎉 

you might also find https://github.com/asottile/reorder_python_imports helpful.  I had the same frustrations with isort and it looks like we went down similar routes 😆 (my testsuite might be of help to you -- plus the testsuite for https://github.com/asottile/aspy.refactor_imports)

**Comment by miki725** [comment]
very cool. thank you @asottile 

sure will take a look

**Comment by asottile** [comment]
<3
