### ISSUE TITLE
Option to disable space added after comment

### ISSUE THREAD

**Issue by commentator8** [miki725/importanize#66]
Space added after empty comment line that doesn't allow for using pre-commit trim_trailing_whitespace. Each one makes a change each time and fails the run.

Would it be possible to add an option to disable adding whitespace as below:

```
# [whitespace added here when line previously ended with #]
# This file is part of pysqlite.
# [whitespace added here when line previously ended with #]
```

**Comment by miki725** [comment]
this sounds like a bug
